# Databricks notebook source
# MAGIC %md
# MAGIC # 31_build_dwh_facts — Working Version
# MAGIC
# MAGIC Bu notebook Silver katmanından Kimball yaklaşımına uygun fact tablolarını oluşturur ve yükler.
# MAGIC
# MAGIC Oluşturulan fact tabloları:
# MAGIC
# MAGIC - `dwh.fact_sales_transaction`
# MAGIC - `dwh.fact_coupon_redemption`
# MAGIC - `dwh.fact_campaign_target`
# MAGIC - `dwh.fact_promotion_weekly`
# MAGIC
# MAGIC ## Grain
# MAGIC
# MAGIC - **fact_sales_transaction:** Bir basket içindeki bir ürün satırı
# MAGIC - **fact_coupon_redemption:** Bir household tarafından bir günde kullanılan bir coupon
# MAGIC - **fact_campaign_target:** Bir campaign'e hedeflenen bir household
# MAGIC - **fact_promotion_weekly:** Bir ürünün bir mağazada bir haftadaki promotion durumu
# MAGIC
# MAGIC Tüm dimension eşleşmeleri surrogate key ile yapılır. Eşleşmeyen kayıtlar `-1` unknown member'a bağlanır.
# MAGIC

# COMMAND ----------

required_parameters = [
    "BatchID",
    "LoadMode",
    "ProcessDate",
    "ProcessDay",
    "ProcessWeek"
]

parameters = {}

for name in required_parameters:
    try:
        value = dbutils.widgets.get(name).strip()
    except Exception as exc:
        raise ValueError(
            f"{name} parametresi notebooka gelmedi."
        ) from exc

    if not value:
        raise ValueError(
            f"{name} parametresi boş geldi."
        )

    parameters[name] = value

print("Gelen parametreler:")
for key, value in parameters.items():
    print(f"{key} = {value!r}")

# COMMAND ----------

# MAGIC %sql
# MAGIC USE CATALOG retail_marketing
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC SELECT
# MAGIC     TRIM(:BatchID) AS BatchID,
# MAGIC     CAST(:ProcessDate AS DATE) AS ProcessDate,
# MAGIC     CAST(:ProcessDay AS DECIMAL(10,0)) AS ProcessDay,
# MAGIC     CAST(:ProcessWeek AS DECIMAL(10,0)) AS ProcessWeek
# MAGIC

# COMMAND ----------

# MAGIC %md
# MAGIC ## 1. Fact tablolarını oluştur
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE IF NOT EXISTS retail_marketing.dwh.fact_sales_transaction (
# MAGIC     SalesFactKey BIGINT GENERATED BY DEFAULT AS IDENTITY,
# MAGIC     HouseholdKey BIGINT,
# MAGIC     ProductKey BIGINT,
# MAGIC     StoreKey BIGINT,
# MAGIC     DayKey BIGINT,
# MAGIC     BasketID DECIMAL(20,0),
# MAGIC     TransactionTime DECIMAL(10,0),
# MAGIC     WeekNumber DECIMAL(10,0),
# MAGIC     Quantity DECIMAL(18,4),
# MAGIC     GrossSalesAmount DECIMAL(18,4),
# MAGIC     RetailDiscountAmount DECIMAL(18,4),
# MAGIC     CouponDiscountAmount DECIMAL(18,4),
# MAGIC     CouponMatchDiscountAmount DECIMAL(18,4),
# MAGIC     TotalDiscountAmount DECIMAL(18,4),
# MAGIC     NetSalesAmount DECIMAL(18,4),
# MAGIC     HasCoupon STRING,
# MAGIC     SourceBatchID STRING,
# MAGIC     ProcessDate DATE,
# MAGIC     CreatedAt TIMESTAMP,
# MAGIC     RecordHash STRING
# MAGIC )
# MAGIC USING DELTA
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE IF NOT EXISTS retail_marketing.dwh.fact_coupon_redemption (
# MAGIC     CouponRedemptionFactKey BIGINT GENERATED BY DEFAULT AS IDENTITY,
# MAGIC     HouseholdKey BIGINT,
# MAGIC     CouponKey BIGINT,
# MAGIC     CampaignKey BIGINT,
# MAGIC     DayKey BIGINT,
# MAGIC     RedemptionCount DECIMAL(18,0),
# MAGIC     SourceBatchID STRING,
# MAGIC     ProcessDate DATE,
# MAGIC     CreatedAt TIMESTAMP,
# MAGIC     RecordHash STRING
# MAGIC )
# MAGIC USING DELTA
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE IF NOT EXISTS retail_marketing.dwh.fact_campaign_target (
# MAGIC     CampaignTargetFactKey BIGINT GENERATED BY DEFAULT AS IDENTITY,
# MAGIC     HouseholdKey BIGINT,
# MAGIC     CampaignKey BIGINT,
# MAGIC     TargetCount DECIMAL(18,0),
# MAGIC     SourceBatchID STRING,
# MAGIC     ProcessDate DATE,
# MAGIC     CreatedAt TIMESTAMP,
# MAGIC     RecordHash STRING
# MAGIC )
# MAGIC USING DELTA
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE IF NOT EXISTS retail_marketing.dwh.fact_promotion_weekly (
# MAGIC     PromotionWeeklyFactKey BIGINT GENERATED BY DEFAULT AS IDENTITY,
# MAGIC     ProductKey BIGINT,
# MAGIC     StoreKey BIGINT,
# MAGIC     WeekNumber DECIMAL(10,0),
# MAGIC     DisplayCode STRING,
# MAGIC     MailerCode STRING,
# MAGIC     HasDisplay STRING,
# MAGIC     HasMailer STRING,
# MAGIC     PromotionCount DECIMAL(18,0),
# MAGIC     SourceBatchID STRING,
# MAGIC     ProcessDate DATE,
# MAGIC     CreatedAt TIMESTAMP,
# MAGIC     RecordHash STRING
# MAGIC )
# MAGIC USING DELTA
# MAGIC

# COMMAND ----------

# MAGIC %md
# MAGIC ## 2. Dimension hazırlık kontrolü
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC SELECT 'dim_product' AS DimensionName, COUNT(*) AS RowCount
# MAGIC FROM retail_marketing.dwh.dim_product
# MAGIC
# MAGIC UNION ALL
# MAGIC
# MAGIC SELECT 'dim_household', COUNT(*)
# MAGIC FROM retail_marketing.dwh.dim_household
# MAGIC
# MAGIC UNION ALL
# MAGIC
# MAGIC SELECT 'dim_campaign', COUNT(*)
# MAGIC FROM retail_marketing.dwh.dim_campaign
# MAGIC
# MAGIC UNION ALL
# MAGIC
# MAGIC SELECT 'dim_store', COUNT(*)
# MAGIC FROM retail_marketing.dwh.dim_store
# MAGIC
# MAGIC UNION ALL
# MAGIC
# MAGIC SELECT 'dim_coupon', COUNT(*)
# MAGIC FROM retail_marketing.dwh.dim_coupon
# MAGIC
# MAGIC UNION ALL
# MAGIC
# MAGIC SELECT 'dim_day', COUNT(*)
# MAGIC FROM retail_marketing.dwh.dim_day
# MAGIC

# COMMAND ----------

# MAGIC %md
# MAGIC ## 3. Sales transaction fact kaynağını hazırla
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE OR REPLACE TEMP VIEW sales_fact_source AS
# MAGIC SELECT
# MAGIC     COALESCE(h.HouseholdKey, -1) AS HouseholdKey,
# MAGIC     COALESCE(p.ProductKey, -1) AS ProductKey,
# MAGIC     COALESCE(s.StoreKey, -1) AS StoreKey,
# MAGIC     COALESCE(d.DayKey, -1) AS DayKey,
# MAGIC
# MAGIC     t.basket_id AS BasketID,
# MAGIC     t.trans_time AS TransactionTime,
# MAGIC     t.week_no AS WeekNumber,
# MAGIC     t.quantity AS Quantity,
# MAGIC
# MAGIC     t.sales_value AS GrossSalesAmount,
# MAGIC     COALESCE(t.retail_disc, 0) AS RetailDiscountAmount,
# MAGIC     COALESCE(t.coupon_disc, 0) AS CouponDiscountAmount,
# MAGIC     COALESCE(t.coupon_match_disc, 0) AS CouponMatchDiscountAmount,
# MAGIC
# MAGIC     ABS(COALESCE(t.retail_disc, 0))
# MAGIC       + ABS(COALESCE(t.coupon_disc, 0))
# MAGIC       + ABS(COALESCE(t.coupon_match_disc, 0)) AS TotalDiscountAmount,
# MAGIC
# MAGIC     t.net_sales_value AS NetSalesAmount,
# MAGIC     t.has_coupon AS HasCoupon,
# MAGIC
# MAGIC     t.SourceBatchID,
# MAGIC     t.ProcessDate,
# MAGIC     t.RecordHash
# MAGIC
# MAGIC FROM retail_marketing.silver.transaction_clean AS t
# MAGIC
# MAGIC LEFT JOIN retail_marketing.dwh.dim_household AS h
# MAGIC     ON h.HouseholdID = t.household_key
# MAGIC    AND h.IsCurrent = TRUE
# MAGIC    AND h.HouseholdKey <> -1
# MAGIC
# MAGIC LEFT JOIN retail_marketing.dwh.dim_product AS p
# MAGIC     ON p.ProductID = t.product_id
# MAGIC    AND p.IsCurrent = TRUE
# MAGIC    AND p.ProductKey <> -1
# MAGIC
# MAGIC LEFT JOIN retail_marketing.dwh.dim_store AS s
# MAGIC     ON s.StoreID = t.store_id
# MAGIC    AND s.IsCurrent = TRUE
# MAGIC    AND s.StoreKey <> -1
# MAGIC
# MAGIC LEFT JOIN retail_marketing.dwh.dim_day AS d
# MAGIC     ON d.DayNumber = t.day_no
# MAGIC    AND d.IsCurrent = TRUE
# MAGIC    AND d.DayKey <> -1
# MAGIC
# MAGIC WHERE t.SourceBatchID = TRIM(:BatchID)
# MAGIC   AND t.day_no = CAST(:ProcessDay AS DECIMAL(10,0))
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC SELECT
# MAGIC     COUNT(*) AS SourceRowCount,
# MAGIC     SUM(CASE WHEN HouseholdKey = -1 THEN 1 ELSE 0 END) AS UnknownHouseholdCount,
# MAGIC     SUM(CASE WHEN ProductKey = -1 THEN 1 ELSE 0 END) AS UnknownProductCount,
# MAGIC     SUM(CASE WHEN StoreKey = -1 THEN 1 ELSE 0 END) AS UnknownStoreCount,
# MAGIC     SUM(CASE WHEN DayKey = -1 THEN 1 ELSE 0 END) AS UnknownDayCount
# MAGIC FROM sales_fact_source
# MAGIC

# COMMAND ----------

# MAGIC %md
# MAGIC ## 4. Sales transaction fact reload
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC DELETE FROM retail_marketing.dwh.fact_sales_transaction
# MAGIC WHERE SourceBatchID = TRIM(:BatchID)
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC INSERT INTO retail_marketing.dwh.fact_sales_transaction (
# MAGIC     HouseholdKey,
# MAGIC     ProductKey,
# MAGIC     StoreKey,
# MAGIC     DayKey,
# MAGIC     BasketID,
# MAGIC     TransactionTime,
# MAGIC     WeekNumber,
# MAGIC     Quantity,
# MAGIC     GrossSalesAmount,
# MAGIC     RetailDiscountAmount,
# MAGIC     CouponDiscountAmount,
# MAGIC     CouponMatchDiscountAmount,
# MAGIC     TotalDiscountAmount,
# MAGIC     NetSalesAmount,
# MAGIC     HasCoupon,
# MAGIC     SourceBatchID,
# MAGIC     ProcessDate,
# MAGIC     CreatedAt,
# MAGIC     RecordHash
# MAGIC )
# MAGIC SELECT
# MAGIC     HouseholdKey,
# MAGIC     ProductKey,
# MAGIC     StoreKey,
# MAGIC     DayKey,
# MAGIC     BasketID,
# MAGIC     TransactionTime,
# MAGIC     WeekNumber,
# MAGIC     Quantity,
# MAGIC     GrossSalesAmount,
# MAGIC     RetailDiscountAmount,
# MAGIC     CouponDiscountAmount,
# MAGIC     CouponMatchDiscountAmount,
# MAGIC     TotalDiscountAmount,
# MAGIC     NetSalesAmount,
# MAGIC     HasCoupon,
# MAGIC     SourceBatchID,
# MAGIC     ProcessDate,
# MAGIC     current_timestamp(),
# MAGIC     RecordHash
# MAGIC FROM sales_fact_source
# MAGIC WHERE EXISTS (
# MAGIC     SELECT 1
# MAGIC     FROM retail_marketing.control.etl_batch_control
# MAGIC     WHERE BatchID = TRIM(:BatchID)
# MAGIC       AND BatchStatus = 'RUNNING'
# MAGIC )
# MAGIC

# COMMAND ----------

# MAGIC %md
# MAGIC ## 5. Coupon redemption fact kaynağını hazırla
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE OR REPLACE TEMP VIEW coupon_redemption_fact_source AS
# MAGIC SELECT
# MAGIC     COALESCE(h.HouseholdKey, -1) AS HouseholdKey,
# MAGIC     COALESCE(c.CouponKey, -1) AS CouponKey,
# MAGIC     COALESCE(cam.CampaignKey, -1) AS CampaignKey,
# MAGIC     COALESCE(d.DayKey, -1) AS DayKey,
# MAGIC
# MAGIC     CAST(1 AS DECIMAL(18,0)) AS RedemptionCount,
# MAGIC     r.SourceBatchID,
# MAGIC     r.ProcessDate,
# MAGIC     r.RecordHash
# MAGIC
# MAGIC FROM retail_marketing.silver.coupon_redemption_clean AS r
# MAGIC
# MAGIC LEFT JOIN retail_marketing.dwh.dim_household AS h
# MAGIC     ON h.HouseholdID = r.household_key
# MAGIC    AND h.IsCurrent = TRUE
# MAGIC    AND h.HouseholdKey <> -1
# MAGIC
# MAGIC LEFT JOIN retail_marketing.dwh.dim_coupon AS c
# MAGIC     ON c.CouponUPC = r.coupon_upc
# MAGIC    AND c.IsCurrent = TRUE
# MAGIC    AND c.CouponKey <> -1
# MAGIC
# MAGIC LEFT JOIN retail_marketing.dwh.dim_campaign AS cam
# MAGIC     ON cam.CampaignID = r.campaign_id
# MAGIC    AND cam.IsCurrent = TRUE
# MAGIC    AND cam.CampaignKey <> -1
# MAGIC
# MAGIC LEFT JOIN retail_marketing.dwh.dim_day AS d
# MAGIC     ON d.DayNumber = r.day_no
# MAGIC    AND d.IsCurrent = TRUE
# MAGIC    AND d.DayKey <> -1
# MAGIC
# MAGIC WHERE r.SourceBatchID = TRIM(:BatchID)
# MAGIC   AND r.day_no = CAST(:ProcessDay AS DECIMAL(10,0))
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC DELETE FROM retail_marketing.dwh.fact_coupon_redemption
# MAGIC WHERE SourceBatchID = TRIM(:BatchID)
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC INSERT INTO retail_marketing.dwh.fact_coupon_redemption (
# MAGIC     HouseholdKey,
# MAGIC     CouponKey,
# MAGIC     CampaignKey,
# MAGIC     DayKey,
# MAGIC     RedemptionCount,
# MAGIC     SourceBatchID,
# MAGIC     ProcessDate,
# MAGIC     CreatedAt,
# MAGIC     RecordHash
# MAGIC )
# MAGIC SELECT
# MAGIC     HouseholdKey,
# MAGIC     CouponKey,
# MAGIC     CampaignKey,
# MAGIC     DayKey,
# MAGIC     RedemptionCount,
# MAGIC     SourceBatchID,
# MAGIC     ProcessDate,
# MAGIC     current_timestamp(),
# MAGIC     RecordHash
# MAGIC FROM coupon_redemption_fact_source
# MAGIC WHERE EXISTS (
# MAGIC     SELECT 1
# MAGIC     FROM retail_marketing.control.etl_batch_control
# MAGIC     WHERE BatchID = TRIM(:BatchID)
# MAGIC       AND BatchStatus = 'RUNNING'
# MAGIC )
# MAGIC

# COMMAND ----------

# MAGIC %md
# MAGIC ## 6. Campaign target fact kaynağını hazırla
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE OR REPLACE TEMP VIEW campaign_target_fact_source AS
# MAGIC SELECT
# MAGIC     COALESCE(h.HouseholdKey, -1) AS HouseholdKey,
# MAGIC     COALESCE(c.CampaignKey, -1) AS CampaignKey,
# MAGIC     CAST(1 AS DECIMAL(18,0)) AS TargetCount,
# MAGIC     t.SourceBatchID,
# MAGIC     t.ProcessDate,
# MAGIC     t.RecordHash
# MAGIC
# MAGIC FROM retail_marketing.silver.campaign_target_clean AS t
# MAGIC
# MAGIC LEFT JOIN retail_marketing.dwh.dim_household AS h
# MAGIC     ON h.HouseholdID = t.household_key
# MAGIC    AND h.IsCurrent = TRUE
# MAGIC    AND h.HouseholdKey <> -1
# MAGIC
# MAGIC LEFT JOIN retail_marketing.dwh.dim_campaign AS c
# MAGIC     ON c.CampaignID = t.campaign_id
# MAGIC    AND c.IsCurrent = TRUE
# MAGIC    AND c.CampaignKey <> -1
# MAGIC
# MAGIC WHERE t.SourceBatchID = TRIM(:BatchID)
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC DELETE FROM retail_marketing.dwh.fact_campaign_target
# MAGIC WHERE SourceBatchID = TRIM(:BatchID)
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC INSERT INTO retail_marketing.dwh.fact_campaign_target (
# MAGIC     HouseholdKey,
# MAGIC     CampaignKey,
# MAGIC     TargetCount,
# MAGIC     SourceBatchID,
# MAGIC     ProcessDate,
# MAGIC     CreatedAt,
# MAGIC     RecordHash
# MAGIC )
# MAGIC SELECT
# MAGIC     HouseholdKey,
# MAGIC     CampaignKey,
# MAGIC     TargetCount,
# MAGIC     SourceBatchID,
# MAGIC     ProcessDate,
# MAGIC     current_timestamp(),
# MAGIC     RecordHash
# MAGIC FROM campaign_target_fact_source
# MAGIC WHERE EXISTS (
# MAGIC     SELECT 1
# MAGIC     FROM retail_marketing.control.etl_batch_control
# MAGIC     WHERE BatchID = TRIM(:BatchID)
# MAGIC       AND BatchStatus = 'RUNNING'
# MAGIC )
# MAGIC

# COMMAND ----------

# MAGIC %md
# MAGIC ## 7. Promotion weekly fact kaynağını hazırla
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE OR REPLACE TEMP VIEW promotion_weekly_fact_source AS
# MAGIC SELECT
# MAGIC     COALESCE(p.ProductKey, -1) AS ProductKey,
# MAGIC     COALESCE(s.StoreKey, -1) AS StoreKey,
# MAGIC
# MAGIC     pr.week_no AS WeekNumber,
# MAGIC     pr.display_code AS DisplayCode,
# MAGIC     pr.mailer_code AS MailerCode,
# MAGIC     pr.has_display AS HasDisplay,
# MAGIC     pr.has_mailer AS HasMailer,
# MAGIC
# MAGIC     CAST(1 AS DECIMAL(18,0)) AS PromotionCount,
# MAGIC     pr.SourceBatchID,
# MAGIC     pr.ProcessDate,
# MAGIC     pr.RecordHash
# MAGIC
# MAGIC FROM retail_marketing.silver.promotion_weekly_clean AS pr
# MAGIC
# MAGIC LEFT JOIN retail_marketing.dwh.dim_product AS p
# MAGIC     ON p.ProductID = pr.product_id
# MAGIC    AND p.IsCurrent = TRUE
# MAGIC    AND p.ProductKey <> -1
# MAGIC
# MAGIC LEFT JOIN retail_marketing.dwh.dim_store AS s
# MAGIC     ON s.StoreID = pr.store_id
# MAGIC    AND s.IsCurrent = TRUE
# MAGIC    AND s.StoreKey <> -1
# MAGIC
# MAGIC WHERE pr.SourceBatchID = TRIM(:BatchID)
# MAGIC   AND pr.week_no = CAST(:ProcessWeek AS DECIMAL(10,0))
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC DELETE FROM retail_marketing.dwh.fact_promotion_weekly
# MAGIC WHERE SourceBatchID = TRIM(:BatchID)
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC INSERT INTO retail_marketing.dwh.fact_promotion_weekly (
# MAGIC     ProductKey,
# MAGIC     StoreKey,
# MAGIC     WeekNumber,
# MAGIC     DisplayCode,
# MAGIC     MailerCode,
# MAGIC     HasDisplay,
# MAGIC     HasMailer,
# MAGIC     PromotionCount,
# MAGIC     SourceBatchID,
# MAGIC     ProcessDate,
# MAGIC     CreatedAt,
# MAGIC     RecordHash
# MAGIC )
# MAGIC SELECT
# MAGIC     ProductKey,
# MAGIC     StoreKey,
# MAGIC     WeekNumber,
# MAGIC     DisplayCode,
# MAGIC     MailerCode,
# MAGIC     HasDisplay,
# MAGIC     HasMailer,
# MAGIC     PromotionCount,
# MAGIC     SourceBatchID,
# MAGIC     ProcessDate,
# MAGIC     current_timestamp(),
# MAGIC     RecordHash
# MAGIC FROM promotion_weekly_fact_source
# MAGIC WHERE EXISTS (
# MAGIC     SELECT 1
# MAGIC     FROM retail_marketing.control.etl_batch_control
# MAGIC     WHERE BatchID = TRIM(:BatchID)
# MAGIC       AND BatchStatus = 'RUNNING'
# MAGIC )
# MAGIC

# COMMAND ----------

# MAGIC %md
# MAGIC ## 8. Fact yükleme loglarını yaz
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC MERGE INTO retail_marketing.audit.etl_table_load_log AS target
# MAGIC USING (
# MAGIC     SELECT
# MAGIC         CONCAT(TRIM(:BatchID), '_DWH_FACT_SALES') AS ETLLogID,
# MAGIC         TRIM(:BatchID) AS BatchID,
# MAGIC         'transaction_clean' AS SourceName,
# MAGIC         'retail_marketing.dwh.fact_sales_transaction' AS TargetTableName,
# MAGIC         CAST(:ProcessDay AS DECIMAL(20,0)) AS ProcessValue,
# MAGIC         (SELECT COUNT(*) FROM sales_fact_source) AS SourceRowCount,
# MAGIC         (
# MAGIC             SELECT COUNT(*)
# MAGIC             FROM retail_marketing.dwh.fact_sales_transaction
# MAGIC             WHERE SourceBatchID = TRIM(:BatchID)
# MAGIC         ) AS InsertedRowCount
# MAGIC
# MAGIC     UNION ALL
# MAGIC
# MAGIC     SELECT
# MAGIC         CONCAT(TRIM(:BatchID), '_DWH_FACT_COUPON_REDEMPTION'),
# MAGIC         TRIM(:BatchID),
# MAGIC         'coupon_redemption_clean',
# MAGIC         'retail_marketing.dwh.fact_coupon_redemption',
# MAGIC         CAST(:ProcessDay AS DECIMAL(20,0)),
# MAGIC         (SELECT COUNT(*) FROM coupon_redemption_fact_source),
# MAGIC         (
# MAGIC             SELECT COUNT(*)
# MAGIC             FROM retail_marketing.dwh.fact_coupon_redemption
# MAGIC             WHERE SourceBatchID = TRIM(:BatchID)
# MAGIC         )
# MAGIC
# MAGIC     UNION ALL
# MAGIC
# MAGIC     SELECT
# MAGIC         CONCAT(TRIM(:BatchID), '_DWH_FACT_CAMPAIGN_TARGET'),
# MAGIC         TRIM(:BatchID),
# MAGIC         'campaign_target_clean',
# MAGIC         'retail_marketing.dwh.fact_campaign_target',
# MAGIC         CAST(NULL AS DECIMAL(20,0)),
# MAGIC         (SELECT COUNT(*) FROM campaign_target_fact_source),
# MAGIC         (
# MAGIC             SELECT COUNT(*)
# MAGIC             FROM retail_marketing.dwh.fact_campaign_target
# MAGIC             WHERE SourceBatchID = TRIM(:BatchID)
# MAGIC         )
# MAGIC
# MAGIC     UNION ALL
# MAGIC
# MAGIC     SELECT
# MAGIC         CONCAT(TRIM(:BatchID), '_DWH_FACT_PROMOTION_WEEKLY'),
# MAGIC         TRIM(:BatchID),
# MAGIC         'promotion_weekly_clean',
# MAGIC         'retail_marketing.dwh.fact_promotion_weekly',
# MAGIC         CAST(:ProcessWeek AS DECIMAL(20,0)),
# MAGIC         (SELECT COUNT(*) FROM promotion_weekly_fact_source),
# MAGIC         (
# MAGIC             SELECT COUNT(*)
# MAGIC             FROM retail_marketing.dwh.fact_promotion_weekly
# MAGIC             WHERE SourceBatchID = TRIM(:BatchID)
# MAGIC         )
# MAGIC ) AS source
# MAGIC
# MAGIC ON target.ETLLogID = source.ETLLogID
# MAGIC
# MAGIC WHEN MATCHED THEN UPDATE SET
# MAGIC     target.BatchID = source.BatchID,
# MAGIC     target.LayerName = 'DWH',
# MAGIC     target.SourceName = source.SourceName,
# MAGIC     target.TargetTableName = source.TargetTableName,
# MAGIC     target.LoadStrategy= 'FACT_RELOAD',
# MAGIC     target.ProcessDate = CAST(:ProcessDate AS DATE),
# MAGIC     target.ProcessValue = source.ProcessValue,
# MAGIC     target.StartTime = current_timestamp(),
# MAGIC     target.EndTime = current_timestamp(),
# MAGIC     target.SourceRowCount = source.SourceRowCount,
# MAGIC     target.InsertedRowCount = source.InsertedRowCount,
# MAGIC     target.UpdatedRowCount = 0,
# MAGIC     target.RejectedRowCount = 0,
# MAGIC     target.UnchangedRowCount = 0,
# MAGIC     target.LoadStatus = CASE
# MAGIC         WHEN source.SourceRowCount = 0
# MAGIC              AND source.SourceName = 'coupon_redemption_clean'
# MAGIC             THEN 'SKIPPED'
# MAGIC         WHEN source.SourceRowCount = 0
# MAGIC             THEN 'FAILED'
# MAGIC         WHEN source.SourceRowCount = source.InsertedRowCount
# MAGIC             THEN 'SUCCESS'
# MAGIC         ELSE 'FAILED'
# MAGIC     END,
# MAGIC     target.ErrorMessage = CASE
# MAGIC         WHEN source.SourceRowCount = 0
# MAGIC              AND source.SourceName = 'coupon_redemption_clean'
# MAGIC             THEN 'ProcessDay için coupon redemption kaydı bulunamadı.'
# MAGIC         WHEN source.SourceRowCount = 0
# MAGIC             THEN 'Fact kaynağı boş.'
# MAGIC         WHEN source.SourceRowCount <> source.InsertedRowCount
# MAGIC             THEN 'Fact kaynak-hedef satır sayıları eşleşmiyor.'
# MAGIC         ELSE NULL
# MAGIC     END,
# MAGIC     target.ETLTime = current_timestamp()
# MAGIC
# MAGIC WHEN NOT MATCHED THEN INSERT (
# MAGIC     ETLLogID,
# MAGIC     BatchID,
# MAGIC     LayerName,
# MAGIC     SourceName,
# MAGIC     TargetTableName,
# MAGIC     LoadStrategy,
# MAGIC     ProcessDate,
# MAGIC     ProcessValue,
# MAGIC     StartTime,
# MAGIC     EndTime,
# MAGIC     SourceRowCount,
# MAGIC     InsertedRowCount,
# MAGIC     UpdatedRowCount,
# MAGIC     RejectedRowCount,
# MAGIC     UnchangedRowCount,
# MAGIC     LoadStatus,
# MAGIC     ErrorMessage,
# MAGIC     ETLTime
# MAGIC )
# MAGIC VALUES (
# MAGIC     source.ETLLogID,
# MAGIC     source.BatchID,
# MAGIC     'DWH',
# MAGIC     source.SourceName,
# MAGIC     source.TargetTableName,
# MAGIC     'FACT_RELOAD',
# MAGIC     CAST(:ProcessDate AS DATE),
# MAGIC     source.ProcessValue,
# MAGIC     current_timestamp(),
# MAGIC     current_timestamp(),
# MAGIC     source.SourceRowCount,
# MAGIC     source.InsertedRowCount,
# MAGIC     0,
# MAGIC     0,
# MAGIC     0,
# MAGIC     CASE
# MAGIC         WHEN source.SourceRowCount = 0
# MAGIC              AND source.SourceName = 'coupon_redemption_clean'
# MAGIC             THEN 'SKIPPED'
# MAGIC         WHEN source.SourceRowCount = 0
# MAGIC             THEN 'FAILED'
# MAGIC         WHEN source.SourceRowCount = source.InsertedRowCount
# MAGIC             THEN 'SUCCESS'
# MAGIC         ELSE 'FAILED'
# MAGIC     END,
# MAGIC     CASE
# MAGIC         WHEN source.SourceRowCount = 0
# MAGIC              AND source.SourceName = 'coupon_redemption_clean'
# MAGIC             THEN 'ProcessDay için coupon redemption kaydı bulunamadı.'
# MAGIC         WHEN source.SourceRowCount = 0
# MAGIC             THEN 'Fact kaynağı boş.'
# MAGIC         WHEN source.SourceRowCount <> source.InsertedRowCount
# MAGIC             THEN 'Fact kaynak-hedef satır sayıları eşleşmiyor.'
# MAGIC         ELSE NULL
# MAGIC     END,
# MAGIC     current_timestamp()
# MAGIC )
# MAGIC

# COMMAND ----------

# MAGIC %md
# MAGIC ## 9. Fact sonuçları
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC SELECT
# MAGIC     'fact_sales_transaction' AS FactTable,
# MAGIC     COUNT(*) AS RowCount
# MAGIC FROM retail_marketing.dwh.fact_sales_transaction
# MAGIC WHERE SourceBatchID = TRIM(:BatchID)
# MAGIC
# MAGIC UNION ALL
# MAGIC
# MAGIC SELECT
# MAGIC     'fact_coupon_redemption',
# MAGIC     COUNT(*)
# MAGIC FROM retail_marketing.dwh.fact_coupon_redemption
# MAGIC WHERE SourceBatchID = TRIM(:BatchID)
# MAGIC
# MAGIC UNION ALL
# MAGIC
# MAGIC SELECT
# MAGIC     'fact_campaign_target',
# MAGIC     COUNT(*)
# MAGIC FROM retail_marketing.dwh.fact_campaign_target
# MAGIC WHERE SourceBatchID = TRIM(:BatchID)
# MAGIC
# MAGIC UNION ALL
# MAGIC
# MAGIC SELECT
# MAGIC     'fact_promotion_weekly',
# MAGIC     COUNT(*)
# MAGIC FROM retail_marketing.dwh.fact_promotion_weekly
# MAGIC WHERE SourceBatchID = TRIM(:BatchID)
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC SELECT
# MAGIC     SourceName,
# MAGIC     TargetTableName,
# MAGIC     ProcessValue,
# MAGIC     SourceRowCount,
# MAGIC     InsertedRowCount,
# MAGIC     LoadStatus,
# MAGIC     ErrorMessage
# MAGIC FROM retail_marketing.audit.etl_table_load_log
# MAGIC WHERE BatchID = TRIM(:BatchID)
# MAGIC   AND LayerName = 'DWH'
# MAGIC ORDER BY SourceName
# MAGIC

# COMMAND ----------

# MAGIC %md
# MAGIC ## 10. Unknown key kontrolleri
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC SELECT
# MAGIC     'fact_sales_transaction' AS FactTable,
# MAGIC     SUM(CASE WHEN HouseholdKey = -1 THEN 1 ELSE 0 END) AS UnknownHouseholdCount,
# MAGIC     SUM(CASE WHEN ProductKey = -1 THEN 1 ELSE 0 END) AS UnknownProductCount,
# MAGIC     SUM(CASE WHEN StoreKey = -1 THEN 1 ELSE 0 END) AS UnknownStoreCount,
# MAGIC     SUM(CASE WHEN DayKey = -1 THEN 1 ELSE 0 END) AS UnknownDayCount
# MAGIC FROM retail_marketing.dwh.fact_sales_transaction
# MAGIC WHERE SourceBatchID = TRIM(:BatchID)
# MAGIC
# MAGIC UNION ALL
# MAGIC
# MAGIC SELECT
# MAGIC     'fact_coupon_redemption',
# MAGIC     SUM(CASE WHEN HouseholdKey = -1 THEN 1 ELSE 0 END),
# MAGIC     SUM(CASE WHEN CouponKey = -1 THEN 1 ELSE 0 END),
# MAGIC     SUM(CASE WHEN CampaignKey = -1 THEN 1 ELSE 0 END),
# MAGIC     SUM(CASE WHEN DayKey = -1 THEN 1 ELSE 0 END)
# MAGIC FROM retail_marketing.dwh.fact_coupon_redemption
# MAGIC WHERE SourceBatchID = TRIM(:BatchID)
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC SELECT
# MAGIC     'fact_sales_transaction' AS TableName,
# MAGIC     COUNT(*) AS RowCount
# MAGIC FROM retail_marketing.dwh.fact_sales_transaction
# MAGIC WHERE SourceBatchID = 'TEST_BATCH_001'
# MAGIC
# MAGIC UNION ALL
# MAGIC
# MAGIC SELECT
# MAGIC     'fact_coupon_redemption',
# MAGIC     COUNT(*)
# MAGIC FROM retail_marketing.dwh.fact_coupon_redemption
# MAGIC WHERE SourceBatchID = 'TEST_BATCH_001'
# MAGIC
# MAGIC UNION ALL
# MAGIC
# MAGIC SELECT
# MAGIC     'fact_campaign_target',
# MAGIC     COUNT(*)
# MAGIC FROM retail_marketing.dwh.fact_campaign_target
# MAGIC WHERE SourceBatchID = 'TEST_BATCH_001'
# MAGIC
# MAGIC UNION ALL
# MAGIC
# MAGIC SELECT
# MAGIC     'fact_promotion_weekly',
# MAGIC     COUNT(*)
# MAGIC FROM retail_marketing.dwh.fact_promotion_weekly
# MAGIC WHERE SourceBatchID = 'TEST_BATCH_001';

# COMMAND ----------

# MAGIC %sql
# MAGIC SELECT
# MAGIC     SourceName,
# MAGIC     TargetTableName,
# MAGIC     SourceRowCount,
# MAGIC     InsertedRowCount,
# MAGIC     LoadStatus,
# MAGIC     ErrorMessage
# MAGIC FROM retail_marketing.audit.etl_table_load_log
# MAGIC WHERE BatchID = 'TEST_BATCH_001'
# MAGIC   AND LayerName = 'DWH'
# MAGIC ORDER BY SourceName;