# Databricks notebook source
# MAGIC %md
# MAGIC # 30_build_dwh_dimensions — Working Version
# MAGIC
# MAGIC Bu notebook Silver katmanından Kimball yaklaşımına uygun DWH dimension tablolarını oluşturur ve yükler.
# MAGIC
# MAGIC Oluşturulan dimension tabloları:
# MAGIC
# MAGIC - `dwh.dim_product`
# MAGIC - `dwh.dim_household`
# MAGIC - `dwh.dim_campaign`
# MAGIC - `dwh.dim_store`
# MAGIC - `dwh.dim_coupon`
# MAGIC - `dwh.dim_day`
# MAGIC
# MAGIC Modelleme kararları:
# MAGIC
# MAGIC - Her dimension için surrogate key kullanılır.
# MAGIC - İlk yüklemede SCD Type 1 uygulanır.
# MAGIC - `-1` surrogate key değeri bilinmeyen/geçersiz üyeyi temsil eder.
# MAGIC - Natural key alanları ayrı tutulur.
# MAGIC - Aynı notebook tekrar çalıştırılabilir.
# MAGIC

# COMMAND ----------

required_parameters = [
    "BatchID",
    "LoadMode",
    "ProcessDate",
    "ProcessDay",
    "ProcessWeek"
]

parameters = {}

for name in required_parameters:
    try:
        value = dbutils.widgets.get(name).strip()
    except Exception as exc:
        raise ValueError(
            f"{name} parametresi notebooka gelmedi."
        ) from exc

    if not value:
        raise ValueError(
            f"{name} parametresi boş geldi."
        )

    parameters[name] = value

print("Gelen parametreler:")
for key, value in parameters.items():
    print(f"{key} = {value!r}")

# COMMAND ----------

# MAGIC %sql
# MAGIC USE CATALOG retail_marketing
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC SELECT
# MAGIC     TRIM(:BatchID) AS BatchID,
# MAGIC     CAST(:ProcessDate AS DATE) AS ProcessDate
# MAGIC

# COMMAND ----------

# MAGIC %md
# MAGIC ## 1. DWH dimension tablolarını oluştur
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE IF NOT EXISTS retail_marketing.dwh.dim_product (
# MAGIC     ProductKey BIGINT GENERATED BY DEFAULT AS IDENTITY,
# MAGIC     ProductID DECIMAL(10,0),
# MAGIC     Manufacturer DECIMAL(10,0),
# MAGIC     Department STRING,
# MAGIC     Brand STRING,
# MAGIC     CommodityDescription STRING,
# MAGIC     SubCommodityDescription STRING,
# MAGIC     CurrentProductSize STRING,
# MAGIC     IsCurrent BOOLEAN,
# MAGIC     SourceBatchID STRING,
# MAGIC     CreatedAt TIMESTAMP,
# MAGIC     UpdatedAt TIMESTAMP,
# MAGIC     RecordHash STRING
# MAGIC )
# MAGIC USING DELTA
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE IF NOT EXISTS retail_marketing.dwh.dim_household (
# MAGIC     HouseholdKey BIGINT GENERATED BY DEFAULT AS IDENTITY,
# MAGIC     HouseholdID DECIMAL(10,0),
# MAGIC     AgeDescription STRING,
# MAGIC     MaritalStatusCode STRING,
# MAGIC     IncomeDescription STRING,
# MAGIC     HomeownerDescription STRING,
# MAGIC     HouseholdCompositionDescription STRING,
# MAGIC     HouseholdSizeDescription STRING,
# MAGIC     KidCategoryDescription STRING,
# MAGIC     IsCurrent BOOLEAN,
# MAGIC     SourceBatchID STRING,
# MAGIC     CreatedAt TIMESTAMP,
# MAGIC     UpdatedAt TIMESTAMP,
# MAGIC     RecordHash STRING
# MAGIC )
# MAGIC USING DELTA
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE IF NOT EXISTS retail_marketing.dwh.dim_campaign (
# MAGIC     CampaignKey BIGINT GENERATED BY DEFAULT AS IDENTITY,
# MAGIC     CampaignID DECIMAL(10,0),
# MAGIC     CampaignDescription STRING,
# MAGIC     StartDay DECIMAL(10,0),
# MAGIC     EndDay DECIMAL(10,0),
# MAGIC     CampaignDuration DECIMAL(10,0),
# MAGIC     IsCurrent BOOLEAN,
# MAGIC     SourceBatchID STRING,
# MAGIC     CreatedAt TIMESTAMP,
# MAGIC     UpdatedAt TIMESTAMP,
# MAGIC     RecordHash STRING
# MAGIC )
# MAGIC USING DELTA
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE IF NOT EXISTS retail_marketing.dwh.dim_store (
# MAGIC     StoreKey BIGINT GENERATED BY DEFAULT AS IDENTITY,
# MAGIC     StoreID DECIMAL(10,0),
# MAGIC     IsCurrent BOOLEAN,
# MAGIC     SourceBatchID STRING,
# MAGIC     CreatedAt TIMESTAMP,
# MAGIC     UpdatedAt TIMESTAMP,
# MAGIC     RecordHash STRING
# MAGIC )
# MAGIC USING DELTA
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE IF NOT EXISTS retail_marketing.dwh.dim_coupon (
# MAGIC     CouponKey BIGINT GENERATED BY DEFAULT AS IDENTITY,
# MAGIC     CouponUPC DECIMAL(20,0),
# MAGIC     CampaignID DECIMAL(10,0),
# MAGIC     IsCurrent BOOLEAN,
# MAGIC     SourceBatchID STRING,
# MAGIC     CreatedAt TIMESTAMP,
# MAGIC     UpdatedAt TIMESTAMP,
# MAGIC     RecordHash STRING
# MAGIC )
# MAGIC USING DELTA
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE IF NOT EXISTS retail_marketing.dwh.dim_day (
# MAGIC     DayKey BIGINT GENERATED BY DEFAULT AS IDENTITY,
# MAGIC     DayNumber DECIMAL(10,0),
# MAGIC     WeekNumber DECIMAL(10,0),
# MAGIC     IsCurrent BOOLEAN,
# MAGIC     SourceBatchID STRING,
# MAGIC     CreatedAt TIMESTAMP,
# MAGIC     UpdatedAt TIMESTAMP,
# MAGIC     RecordHash STRING
# MAGIC )
# MAGIC USING DELTA
# MAGIC

# COMMAND ----------

# MAGIC %md
# MAGIC ## 2. Unknown dimension kayıtlarını oluştur
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC INSERT INTO retail_marketing.dwh.dim_product (
# MAGIC     ProductKey, ProductID, Manufacturer, Department, Brand,
# MAGIC     CommodityDescription, SubCommodityDescription, CurrentProductSize,
# MAGIC     IsCurrent, SourceBatchID, CreatedAt, UpdatedAt, RecordHash
# MAGIC )
# MAGIC SELECT
# MAGIC     -1, -1, -1, 'UNKNOWN', 'UNKNOWN',
# MAGIC     'UNKNOWN', 'UNKNOWN', 'UNKNOWN',
# MAGIC     TRUE, 'SYSTEM', current_timestamp(), current_timestamp(), 'UNKNOWN'
# MAGIC WHERE NOT EXISTS (
# MAGIC     SELECT 1
# MAGIC     FROM retail_marketing.dwh.dim_product
# MAGIC     WHERE ProductKey = -1
# MAGIC )
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC INSERT INTO retail_marketing.dwh.dim_household (
# MAGIC     HouseholdKey, HouseholdID, AgeDescription, MaritalStatusCode,
# MAGIC     IncomeDescription, HomeownerDescription,
# MAGIC     HouseholdCompositionDescription, HouseholdSizeDescription,
# MAGIC     KidCategoryDescription, IsCurrent, SourceBatchID,
# MAGIC     CreatedAt, UpdatedAt, RecordHash
# MAGIC )
# MAGIC SELECT
# MAGIC     -1, -1, 'UNKNOWN', 'UNKNOWN',
# MAGIC     'UNKNOWN', 'UNKNOWN',
# MAGIC     'UNKNOWN', 'UNKNOWN',
# MAGIC     'UNKNOWN', TRUE, 'SYSTEM',
# MAGIC     current_timestamp(), current_timestamp(), 'UNKNOWN'
# MAGIC WHERE NOT EXISTS (
# MAGIC     SELECT 1
# MAGIC     FROM retail_marketing.dwh.dim_household
# MAGIC     WHERE HouseholdKey = -1
# MAGIC )
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC INSERT INTO retail_marketing.dwh.dim_campaign (
# MAGIC     CampaignKey, CampaignID, CampaignDescription,
# MAGIC     StartDay, EndDay, CampaignDuration,
# MAGIC     IsCurrent, SourceBatchID, CreatedAt, UpdatedAt, RecordHash
# MAGIC )
# MAGIC SELECT
# MAGIC     -1, -1, 'UNKNOWN',
# MAGIC     NULL, NULL, NULL,
# MAGIC     TRUE, 'SYSTEM', current_timestamp(), current_timestamp(), 'UNKNOWN'
# MAGIC WHERE NOT EXISTS (
# MAGIC     SELECT 1
# MAGIC     FROM retail_marketing.dwh.dim_campaign
# MAGIC     WHERE CampaignKey = -1
# MAGIC )
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC INSERT INTO retail_marketing.dwh.dim_store (
# MAGIC     StoreKey, StoreID, IsCurrent, SourceBatchID,
# MAGIC     CreatedAt, UpdatedAt, RecordHash
# MAGIC )
# MAGIC SELECT
# MAGIC     -1, -1, TRUE, 'SYSTEM',
# MAGIC     current_timestamp(), current_timestamp(), 'UNKNOWN'
# MAGIC WHERE NOT EXISTS (
# MAGIC     SELECT 1
# MAGIC     FROM retail_marketing.dwh.dim_store
# MAGIC     WHERE StoreKey = -1
# MAGIC )
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC INSERT INTO retail_marketing.dwh.dim_coupon (
# MAGIC     CouponKey, CouponUPC, CampaignID, IsCurrent,
# MAGIC     SourceBatchID, CreatedAt, UpdatedAt, RecordHash
# MAGIC )
# MAGIC SELECT
# MAGIC     -1, -1, -1, TRUE,
# MAGIC     'SYSTEM', current_timestamp(), current_timestamp(), 'UNKNOWN'
# MAGIC WHERE NOT EXISTS (
# MAGIC     SELECT 1
# MAGIC     FROM retail_marketing.dwh.dim_coupon
# MAGIC     WHERE CouponKey = -1
# MAGIC )
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC INSERT INTO retail_marketing.dwh.dim_day (
# MAGIC     DayKey, DayNumber, WeekNumber, IsCurrent,
# MAGIC     SourceBatchID, CreatedAt, UpdatedAt, RecordHash
# MAGIC )
# MAGIC SELECT
# MAGIC     -1, -1, -1, TRUE,
# MAGIC     'SYSTEM', current_timestamp(), current_timestamp(), 'UNKNOWN'
# MAGIC WHERE NOT EXISTS (
# MAGIC     SELECT 1
# MAGIC     FROM retail_marketing.dwh.dim_day
# MAGIC     WHERE DayKey = -1
# MAGIC )
# MAGIC

# COMMAND ----------

# MAGIC %md
# MAGIC ## 3. Product dimension — SCD Type 1
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC MERGE INTO retail_marketing.dwh.dim_product AS target
# MAGIC USING (
# MAGIC     SELECT
# MAGIC         product_id AS ProductID,
# MAGIC         manufacturer AS Manufacturer,
# MAGIC         department AS Department,
# MAGIC         brand AS Brand,
# MAGIC         commodity_desc AS CommodityDescription,
# MAGIC         sub_commodity_desc AS SubCommodityDescription,
# MAGIC         curr_size_of_product AS CurrentProductSize,
# MAGIC         SourceBatchID,
# MAGIC         RecordHash
# MAGIC     FROM retail_marketing.silver.product_clean
# MAGIC     WHERE SourceBatchID = TRIM(:BatchID)
# MAGIC ) AS source
# MAGIC ON target.ProductID = source.ProductID
# MAGIC AND target.ProductKey <> -1
# MAGIC
# MAGIC WHEN MATCHED AND target.RecordHash <> source.RecordHash THEN UPDATE SET
# MAGIC     target.Manufacturer = source.Manufacturer,
# MAGIC     target.Department = source.Department,
# MAGIC     target.Brand = source.Brand,
# MAGIC     target.CommodityDescription = source.CommodityDescription,
# MAGIC     target.SubCommodityDescription = source.SubCommodityDescription,
# MAGIC     target.CurrentProductSize = source.CurrentProductSize,
# MAGIC     target.IsCurrent = TRUE,
# MAGIC     target.SourceBatchID = source.SourceBatchID,
# MAGIC     target.UpdatedAt = current_timestamp(),
# MAGIC     target.RecordHash = source.RecordHash
# MAGIC
# MAGIC WHEN NOT MATCHED THEN INSERT (
# MAGIC     ProductID, Manufacturer, Department, Brand,
# MAGIC     CommodityDescription, SubCommodityDescription,
# MAGIC     CurrentProductSize, IsCurrent, SourceBatchID,
# MAGIC     CreatedAt, UpdatedAt, RecordHash
# MAGIC )
# MAGIC VALUES (
# MAGIC     source.ProductID, source.Manufacturer, source.Department, source.Brand,
# MAGIC     source.CommodityDescription, source.SubCommodityDescription,
# MAGIC     source.CurrentProductSize, TRUE, source.SourceBatchID,
# MAGIC     current_timestamp(), current_timestamp(), source.RecordHash
# MAGIC )
# MAGIC

# COMMAND ----------

# MAGIC %md
# MAGIC ## 4. Household dimension — SCD Type 1
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC MERGE INTO retail_marketing.dwh.dim_household AS target
# MAGIC USING (
# MAGIC     SELECT
# MAGIC         household_key AS HouseholdID,
# MAGIC         age_desc AS AgeDescription,
# MAGIC         marital_status_code AS MaritalStatusCode,
# MAGIC         income_desc AS IncomeDescription,
# MAGIC         homeowner_desc AS HomeownerDescription,
# MAGIC         hh_comp_desc AS HouseholdCompositionDescription,
# MAGIC         household_size_desc AS HouseholdSizeDescription,
# MAGIC         kid_category_desc AS KidCategoryDescription,
# MAGIC         SourceBatchID,
# MAGIC         RecordHash
# MAGIC     FROM retail_marketing.silver.household_demographic_clean
# MAGIC     WHERE SourceBatchID = TRIM(:BatchID)
# MAGIC ) AS source
# MAGIC ON target.HouseholdID = source.HouseholdID
# MAGIC AND target.HouseholdKey <> -1
# MAGIC
# MAGIC WHEN MATCHED AND target.RecordHash <> source.RecordHash THEN UPDATE SET
# MAGIC     target.AgeDescription = source.AgeDescription,
# MAGIC     target.MaritalStatusCode = source.MaritalStatusCode,
# MAGIC     target.IncomeDescription = source.IncomeDescription,
# MAGIC     target.HomeownerDescription = source.HomeownerDescription,
# MAGIC     target.HouseholdCompositionDescription = source.HouseholdCompositionDescription,
# MAGIC     target.HouseholdSizeDescription = source.HouseholdSizeDescription,
# MAGIC     target.KidCategoryDescription = source.KidCategoryDescription,
# MAGIC     target.IsCurrent = TRUE,
# MAGIC     target.SourceBatchID = source.SourceBatchID,
# MAGIC     target.UpdatedAt = current_timestamp(),
# MAGIC     target.RecordHash = source.RecordHash
# MAGIC
# MAGIC WHEN NOT MATCHED THEN INSERT (
# MAGIC     HouseholdID, AgeDescription, MaritalStatusCode,
# MAGIC     IncomeDescription, HomeownerDescription,
# MAGIC     HouseholdCompositionDescription, HouseholdSizeDescription,
# MAGIC     KidCategoryDescription, IsCurrent, SourceBatchID,
# MAGIC     CreatedAt, UpdatedAt, RecordHash
# MAGIC )
# MAGIC VALUES (
# MAGIC     source.HouseholdID, source.AgeDescription, source.MaritalStatusCode,
# MAGIC     source.IncomeDescription, source.HomeownerDescription,
# MAGIC     source.HouseholdCompositionDescription, source.HouseholdSizeDescription,
# MAGIC     source.KidCategoryDescription, TRUE, source.SourceBatchID,
# MAGIC     current_timestamp(), current_timestamp(), source.RecordHash
# MAGIC )
# MAGIC

# COMMAND ----------

# MAGIC %md
# MAGIC ## 5. Campaign dimension — SCD Type 1
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC MERGE INTO retail_marketing.dwh.dim_campaign AS target
# MAGIC USING (
# MAGIC     SELECT
# MAGIC         campaign_id AS CampaignID,
# MAGIC         description AS CampaignDescription,
# MAGIC         start_day AS StartDay,
# MAGIC         end_day AS EndDay,
# MAGIC         campaign_duration AS CampaignDuration,
# MAGIC         SourceBatchID,
# MAGIC         RecordHash
# MAGIC     FROM retail_marketing.silver.campaign_clean
# MAGIC     WHERE SourceBatchID = TRIM(:BatchID)
# MAGIC ) AS source
# MAGIC ON target.CampaignID = source.CampaignID
# MAGIC AND target.CampaignKey <> -1
# MAGIC
# MAGIC WHEN MATCHED AND target.RecordHash <> source.RecordHash THEN UPDATE SET
# MAGIC     target.CampaignDescription = source.CampaignDescription,
# MAGIC     target.StartDay = source.StartDay,
# MAGIC     target.EndDay = source.EndDay,
# MAGIC     target.CampaignDuration = source.CampaignDuration,
# MAGIC     target.IsCurrent = TRUE,
# MAGIC     target.SourceBatchID = source.SourceBatchID,
# MAGIC     target.UpdatedAt = current_timestamp(),
# MAGIC     target.RecordHash = source.RecordHash
# MAGIC
# MAGIC WHEN NOT MATCHED THEN INSERT (
# MAGIC     CampaignID, CampaignDescription, StartDay, EndDay,
# MAGIC     CampaignDuration, IsCurrent, SourceBatchID,
# MAGIC     CreatedAt, UpdatedAt, RecordHash
# MAGIC )
# MAGIC VALUES (
# MAGIC     source.CampaignID, source.CampaignDescription,
# MAGIC     source.StartDay, source.EndDay,
# MAGIC     source.CampaignDuration, TRUE, source.SourceBatchID,
# MAGIC     current_timestamp(), current_timestamp(), source.RecordHash
# MAGIC )
# MAGIC

# COMMAND ----------

# MAGIC %md
# MAGIC ## 6. Store dimension — Silver transaction ve promotion kaynaklarından
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE OR REPLACE TEMP VIEW store_dimension_source AS
# MAGIC SELECT DISTINCT
# MAGIC     StoreID,
# MAGIC     SHA2(CAST(StoreID AS STRING), 256) AS RecordHash
# MAGIC FROM (
# MAGIC     SELECT store_id AS StoreID
# MAGIC     FROM retail_marketing.silver.transaction_clean
# MAGIC     WHERE SourceBatchID = TRIM(:BatchID)
# MAGIC       AND store_id IS NOT NULL
# MAGIC
# MAGIC     UNION
# MAGIC
# MAGIC     SELECT store_id AS StoreID
# MAGIC     FROM retail_marketing.silver.promotion_weekly_clean
# MAGIC     WHERE SourceBatchID = TRIM(:BatchID)
# MAGIC       AND store_id IS NOT NULL
# MAGIC )
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC MERGE INTO retail_marketing.dwh.dim_store AS target
# MAGIC USING store_dimension_source AS source
# MAGIC ON target.StoreID = source.StoreID
# MAGIC AND target.StoreKey <> -1
# MAGIC
# MAGIC WHEN MATCHED AND target.RecordHash <> source.RecordHash THEN UPDATE SET
# MAGIC     target.IsCurrent = TRUE,
# MAGIC     target.SourceBatchID = TRIM(:BatchID),
# MAGIC     target.UpdatedAt = current_timestamp(),
# MAGIC     target.RecordHash = source.RecordHash
# MAGIC
# MAGIC WHEN NOT MATCHED THEN INSERT (
# MAGIC     StoreID, IsCurrent, SourceBatchID,
# MAGIC     CreatedAt, UpdatedAt, RecordHash
# MAGIC )
# MAGIC VALUES (
# MAGIC     source.StoreID, TRUE, TRIM(:BatchID),
# MAGIC     current_timestamp(), current_timestamp(), source.RecordHash
# MAGIC )
# MAGIC

# COMMAND ----------

# MAGIC %md
# MAGIC ## 7. Coupon dimension
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE OR REPLACE TEMP VIEW coupon_dimension_source AS
# MAGIC SELECT
# MAGIC     CouponUPC,
# MAGIC     MAX(CampaignID) AS CampaignID,
# MAGIC     SHA2(
# MAGIC         CONCAT_WS(
# MAGIC             '||',
# MAGIC             CAST(CouponUPC AS STRING),
# MAGIC             CAST(MAX(CampaignID) AS STRING)
# MAGIC         ),
# MAGIC         256
# MAGIC     ) AS RecordHash
# MAGIC FROM (
# MAGIC     SELECT
# MAGIC         coupon_upc AS CouponUPC,
# MAGIC         campaign_id AS CampaignID
# MAGIC     FROM retail_marketing.silver.coupon_product_clean
# MAGIC     WHERE SourceBatchID = TRIM(:BatchID)
# MAGIC       AND coupon_upc IS NOT NULL
# MAGIC
# MAGIC     UNION ALL
# MAGIC
# MAGIC     SELECT
# MAGIC         coupon_upc AS CouponUPC,
# MAGIC         campaign_id AS CampaignID
# MAGIC     FROM retail_marketing.silver.coupon_redemption_clean
# MAGIC     WHERE SourceBatchID = TRIM(:BatchID)
# MAGIC       AND coupon_upc IS NOT NULL
# MAGIC )
# MAGIC GROUP BY CouponUPC
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC MERGE INTO retail_marketing.dwh.dim_coupon AS target
# MAGIC USING coupon_dimension_source AS source
# MAGIC ON target.CouponUPC = source.CouponUPC
# MAGIC AND target.CouponKey <> -1
# MAGIC
# MAGIC WHEN MATCHED AND target.RecordHash <> source.RecordHash THEN UPDATE SET
# MAGIC     target.CampaignID = source.CampaignID,
# MAGIC     target.IsCurrent = TRUE,
# MAGIC     target.SourceBatchID = TRIM(:BatchID),
# MAGIC     target.UpdatedAt = current_timestamp(),
# MAGIC     target.RecordHash = source.RecordHash
# MAGIC
# MAGIC WHEN NOT MATCHED THEN INSERT (
# MAGIC     CouponUPC, CampaignID, IsCurrent,
# MAGIC     SourceBatchID, CreatedAt, UpdatedAt, RecordHash
# MAGIC )
# MAGIC VALUES (
# MAGIC     source.CouponUPC, source.CampaignID, TRUE,
# MAGIC     TRIM(:BatchID), current_timestamp(), current_timestamp(), source.RecordHash
# MAGIC )
# MAGIC

# COMMAND ----------

# MAGIC %md
# MAGIC ## 8. Day dimension
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE OR REPLACE TEMP VIEW day_dimension_source AS
# MAGIC SELECT
# MAGIC     DayNumber,
# MAGIC     MAX(WeekNumber) AS WeekNumber,
# MAGIC     SHA2(
# MAGIC         CONCAT_WS(
# MAGIC             '||',
# MAGIC             CAST(DayNumber AS STRING),
# MAGIC             CAST(MAX(WeekNumber) AS STRING)
# MAGIC         ),
# MAGIC         256
# MAGIC     ) AS RecordHash
# MAGIC FROM (
# MAGIC     SELECT
# MAGIC         day_no AS DayNumber,
# MAGIC         week_no AS WeekNumber
# MAGIC     FROM retail_marketing.silver.transaction_clean
# MAGIC     WHERE SourceBatchID = TRIM(:BatchID)
# MAGIC       AND day_no IS NOT NULL
# MAGIC
# MAGIC     UNION ALL
# MAGIC
# MAGIC     SELECT
# MAGIC         day_no AS DayNumber,
# MAGIC         CAST(NULL AS DECIMAL(10,0)) AS WeekNumber
# MAGIC     FROM retail_marketing.silver.coupon_redemption_clean
# MAGIC     WHERE SourceBatchID = TRIM(:BatchID)
# MAGIC       AND day_no IS NOT NULL
# MAGIC )
# MAGIC GROUP BY DayNumber
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC MERGE INTO retail_marketing.dwh.dim_day AS target
# MAGIC USING day_dimension_source AS source
# MAGIC ON target.DayNumber = source.DayNumber
# MAGIC AND target.DayKey <> -1
# MAGIC
# MAGIC WHEN MATCHED AND target.RecordHash <> source.RecordHash THEN UPDATE SET
# MAGIC     target.WeekNumber = source.WeekNumber,
# MAGIC     target.IsCurrent = TRUE,
# MAGIC     target.SourceBatchID = TRIM(:BatchID),
# MAGIC     target.UpdatedAt = current_timestamp(),
# MAGIC     target.RecordHash = source.RecordHash
# MAGIC
# MAGIC WHEN NOT MATCHED THEN INSERT (
# MAGIC     DayNumber, WeekNumber, IsCurrent,
# MAGIC     SourceBatchID, CreatedAt, UpdatedAt, RecordHash
# MAGIC )
# MAGIC VALUES (
# MAGIC     source.DayNumber, source.WeekNumber, TRUE,
# MAGIC     TRIM(:BatchID), current_timestamp(), current_timestamp(), source.RecordHash
# MAGIC )
# MAGIC

# COMMAND ----------

# MAGIC %md
# MAGIC ## 9. Dimension yükleme sonuçları
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC SELECT 'dim_product' AS DimensionName, COUNT(*) AS RowCount
# MAGIC FROM retail_marketing.dwh.dim_product
# MAGIC
# MAGIC UNION ALL
# MAGIC
# MAGIC SELECT 'dim_household', COUNT(*)
# MAGIC FROM retail_marketing.dwh.dim_household
# MAGIC
# MAGIC UNION ALL
# MAGIC
# MAGIC SELECT 'dim_campaign', COUNT(*)
# MAGIC FROM retail_marketing.dwh.dim_campaign
# MAGIC
# MAGIC UNION ALL
# MAGIC
# MAGIC SELECT 'dim_store', COUNT(*)
# MAGIC FROM retail_marketing.dwh.dim_store
# MAGIC
# MAGIC UNION ALL
# MAGIC
# MAGIC SELECT 'dim_coupon', COUNT(*)
# MAGIC FROM retail_marketing.dwh.dim_coupon
# MAGIC
# MAGIC UNION ALL
# MAGIC
# MAGIC SELECT 'dim_day', COUNT(*)
# MAGIC FROM retail_marketing.dwh.dim_day
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC SELECT
# MAGIC     'dim_product' AS DimensionName,
# MAGIC     COUNT(*) AS DuplicateNaturalKeyCount
# MAGIC FROM (
# MAGIC     SELECT ProductID
# MAGIC     FROM retail_marketing.dwh.dim_product
# MAGIC     WHERE ProductKey <> -1
# MAGIC     GROUP BY ProductID
# MAGIC     HAVING COUNT(*) > 1
# MAGIC )
# MAGIC
# MAGIC UNION ALL
# MAGIC
# MAGIC SELECT
# MAGIC     'dim_household',
# MAGIC     COUNT(*)
# MAGIC FROM (
# MAGIC     SELECT HouseholdID
# MAGIC     FROM retail_marketing.dwh.dim_household
# MAGIC     WHERE HouseholdKey <> -1
# MAGIC     GROUP BY HouseholdID
# MAGIC     HAVING COUNT(*) > 1
# MAGIC )
# MAGIC
# MAGIC UNION ALL
# MAGIC
# MAGIC SELECT
# MAGIC     'dim_campaign',
# MAGIC     COUNT(*)
# MAGIC FROM (
# MAGIC     SELECT CampaignID
# MAGIC     FROM retail_marketing.dwh.dim_campaign
# MAGIC     WHERE CampaignKey <> -1
# MAGIC     GROUP BY CampaignID
# MAGIC     HAVING COUNT(*) > 1
# MAGIC )
# MAGIC
# MAGIC UNION ALL
# MAGIC
# MAGIC SELECT
# MAGIC     'dim_store',
# MAGIC     COUNT(*)
# MAGIC FROM (
# MAGIC     SELECT StoreID
# MAGIC     FROM retail_marketing.dwh.dim_store
# MAGIC     WHERE StoreKey <> -1
# MAGIC     GROUP BY StoreID
# MAGIC     HAVING COUNT(*) > 1
# MAGIC )
# MAGIC
# MAGIC UNION ALL
# MAGIC
# MAGIC SELECT
# MAGIC     'dim_coupon',
# MAGIC     COUNT(*)
# MAGIC FROM (
# MAGIC     SELECT CouponUPC
# MAGIC     FROM retail_marketing.dwh.dim_coupon
# MAGIC     WHERE CouponKey <> -1
# MAGIC     GROUP BY CouponUPC
# MAGIC     HAVING COUNT(*) > 1
# MAGIC )
# MAGIC
# MAGIC UNION ALL
# MAGIC
# MAGIC SELECT
# MAGIC     'dim_day',
# MAGIC     COUNT(*)
# MAGIC FROM (
# MAGIC     SELECT DayNumber
# MAGIC     FROM retail_marketing.dwh.dim_day
# MAGIC     WHERE DayKey <> -1
# MAGIC     GROUP BY DayNumber
# MAGIC     HAVING COUNT(*) > 1
# MAGIC )
# MAGIC